kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: local-storage-metrics
  namespace: openshift-local-storage
rules:
 - apiGroups:
   - ""
   resources:
    - services
    - endpoints
    - pods
   verbs:
    - get
    - list
    - watch
