apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: lso-metrics-serving-cert
  name: lso-metrics-exporter
  namespace: openshift-local-storage
  labels:
    app: lso-metrics-exporter
spec:
  type: ClusterIP
  ports:
  - name: metrics
    port: 8383
    protocol: TCP
    targetPort: metrics
  selector:
    app: lso-metrics-exporter
